### PR TITLE
Fix /tell override crash when used without recipient or message

### LINKED ISSUE #112: /tell not handling self recipient
> SoloSniper: using `/tell <your-username>` crashes server

And stack trace follows:

```
2023-07-08 19:13:01: ERROR[Main]: ServerError: AsyncErr: Lua: Runtime error from mod 'mesecons_commandblock' in callback on_chat_message(): /data/world//worldmods/beerchat/plugin/mute.lua:3: bad argument #1 to 'get_player_by_name' (string expected, got nil)
2023-07-08 19:13:01: ERROR[Main]: stack traceback:
2023-07-08 19:13:01: ERROR[Main]: 	[C]: in function 'get_player_by_name'
2023-07-08 19:13:01: ERROR[Main]: 	/data/world//worldmods/beerchat/plugin/mute.lua:3: in function 'is_muted'
2023-07-08 19:13:01: ERROR[Main]: 	/data/world//worldmods/beerchat/plugin/mute.lua:14: in function 'fn'
2023-07-08 19:13:01: ERROR[Main]: 	/data/world//worldmods/beerchat/hooks.lua:65: in function 'execute_callbacks'
2023-07-08 19:13:01: ERROR[Main]: 	/data/world//worldmods/beerchat/plugin/override.lua:12: in function 'func'
2023-07-08 19:13:01: ERROR[Main]: 	/usr/local/share/minetest/builtin/game/chat.lua:79: in function </usr/local/share/minetest/builtin/game/chat.lua:52>
2023-07-08 19:13:01: ERROR[Main]: 	/usr/local/share/minetest/builtin/game/register.lua:446: in function </usr/local/share/minetest/builtin/game/register.lua:432>
```

Might be `is_muted` or something around it should be changed a bit so that it is able to tolerate weird input.

### PR DESCRIPTION
**Pull request by S-S-X**
Some tests for #112 

When done, fix #112

### CODE REVIEW

**Comment by S-S-X** [comment]
Prob fine but not sure how is_muted should actually behave if target is nil, despite what I said before I think I'm leaning towards letting it crash.

Maybe it should throw warning to logs, after all it is something that should not normally happen.

Or maybe after all it shouldn't actually check for invalid input but just let it crash so that actual underlying issue, that might well break other things, wont get hidden.

**Review by BuckarooBanzay — APPROVED** [review]

**Comment by S-S-X** [comment]
am going to change it and make it clear that target is needed for mute check.

**Comment by S-S-X** [comment]
Changed to allow original mesecons `/tell` to handle empty target parameter.
And changed pattern to allow calling through checks even if there was no message after recipient.
And changed is_muted resilience to assertion to make responsibilities of caller clear and to keep root cause visible.

**Comment by BuckarooBanzay** [comment]
> @BuckarooBanzay what do you think about update? My reasoning for changes is that I think first version was actually very bad because it would hide root cause for issues that could anyway easily emerge elsewhere in callback chain.

looks good :+1:

**Pull request merged**
