### PR TITLE
drafting !status relay command

### PR DESCRIPTION
**Pull request by SwissalpS**
adds ```!status``` relay command.

WIP

### CODE REVIEW

**Comment by SwissalpS** [comment]
ready for testing

**Comment by wsor4035** [comment]
> ready for testing

please take this out of draft then

**Review by wsor4035 — APPROVED** [review]
looks correct. assuming it was tested

**Comment by SwissalpS** [comment]
worked in singleplayer tool use context. Didn't test without any connected players etc.

But I just found out that, at least in newest version, minetest.get_server_status() works passing nil as player.
So I'm going to use that so anybody using scripts to parse that output will have same input format.

**Review by wsor4035 — APPROVED** [review]

**Comment by BuckarooBanzay** [comment]
nice :+1:

**Pull request merged**
